from .actuators import ActuatorWidget
from .video import VideoWidget
from .depth import DepthWidget
from .gyroscope import GyroscopeWidget
from .heading import HeadingWidget
from .logs import RovPiLogWidget
from .temperature import TemperatureWidget
from .thrusters import ThrustersWidget
from .controller import ControllerWidget
