from .actuators import ActuatorWidget
from .video import VideoWidget
from .depth import DepthWidget
from .gyroscope import GyroscopeWidget
from .heading import HeadingWidget
from .console import PiConsoleWidget
from .temperature import TemperatureWidget
from .thrusters import ThrustersWidget
from .controller import ControllerWidget
